---
  - name: first-paly
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: install apache
        apt: 
          name: apache2
          state: latest
      - name: start the service
        service: 
          name: apache2
          state: started  
      - name: copy index.html
        copy: 
          src: index.html
          dest: /home/index.html